on:
  push:
    branches: '*'

name: Build-Docker

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[docker]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xiangyunhuang/masr
          tags: latest

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: xiangyunhuang/masr/masr-book
          tag_with_ref: true

      - name: Check docker container
        uses: docker://xiangyunhuang/masr
        with:
          args:
            - bash -c
            - |
              locale
              xetex --version
              fc-list | sort
              python3 -V
              pandoc -v
              odbcinst -j
              Rscript -e 'sessionInfo(.packages(T)); extSoftVersion(); capabilities(); .libPaths(); version; odbc::odbcListDrivers()'
              echo '\documentclass{article}\begin{document}hello\end{document}' > test.tex; pdflatex test.tex

