on:
  push:
    branches:
      - master # devel

name: Build-Docker

jobs:
  build:
#    if: "contains(github.event.head_commit.message, '[docker]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          cache-from: type=registry,ref=xiangyunhuang/masr:latest
          cache-to: type=inline
          tags: |
            xiangyunhuang/masr:latest
            xiangyunhuang/masr:1.0.0
            ghcr.io/xiangyunhuang/masr:latest
            ghcr.io/xiangyunhuang/masr:1.0.0

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Check docker container
        uses: docker://xiangyunhuang/masr
        with:
          args: bash -c "locale; xetex --version; fc-list | sort; python3 -V; pandoc -v; odbcinst -j; Rscript -e 'sessionInfo(.packages(T)); extSoftVersion(); capabilities(); .libPaths(); version; odbc::odbcListDrivers()'; echo '\documentclass{article}\begin{document}hello\end{document}' > test.tex; xelatex test.tex"
