on:
  push:
    branches:
      - master # devel

name: Build-Docker

jobs:
  build:
#    if: "contains(github.event.head_commit.message, '[docker]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=xiangyunhuang/masr
          cache-to: type=registry,ref=xiangyunhuang/masr
          tags: xiangyunhuang/masr:latest

      # - name: Push to GitHub Packages
      #   uses: docker/build-push-action@v2
      #   with:
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     registry: docker.pkg.github.com
      #     repository: xiangyunhuang/masr/masr-book
      #     tag_with_ref: true

      - name: Check docker container
        uses: docker://xiangyunhuang/masr
        with:
          args: bash -c "locale; xetex --version; fc-list | sort; python3 -V; pandoc -v; odbcinst -j; Rscript -e 'sessionInfo(.packages(T)); extSoftVersion(); capabilities(); .libPaths(); version; odbc::odbcListDrivers()'; echo '\documentclass{article}\begin{document}hello\end{document}' > test.tex; xelatex test.tex"
