on:
  push:
    branches:
      - devel
    paths-ignore:
      - 'examples/**'
  pull_request:
    branches:
      - devel
  schedule:
    # 每周一晚上11点跑任务
    - cron:  '0 23 * * 1'

name: Render-Book

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      matrix:
        config:
          - {os: ubuntu-20.04, r: '4.0.2'}

    env:
      RETICULATE_PYTHON_ENV: "/opt/.virtualenvs/r-tensorflow"
      LANG: "en_US.UTF-8"
      TZ: "Asia/Shanghai"
      CMDSTAN_VERSION: "2.24.1"
      CMDSTAN: "/opt/cmdstan/cmdstan-2.24.1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          ref: 'devel'

      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.10.1'

      - name: Install ghostscript and Others
        run: |
          sudo apt-get install -y cargo ffmpeg graphviz optipng jags virtualenv xvfb python3-virtualenv python3-tk libglpk-dev libgit2-dev fontconfig
          sudo apt-get install -y libpoppler-cpp-dev libmagick++-dev libglu1-mesa-dev libnlopt-dev libudunits2-dev libgdal-dev libproj-dev
          sudo apt-get install -y libnode-dev libgmp-dev libmpfr-dev libmpc-dev

      - name: Install TinyTeX
        run: |
          Rscript -e 'install.packages("tinytex"); tinytex:::install_prebuilt(); tinytex::tinytex_root()'
          export PATH=$HOME/bin:$PATH
          Rscript -e 'tinytex::tlmgr_install(readLines("texlive.txt"))'


      - name: Install Python ENV
        run: |
          virtualenv -p /usr/bin/python3 $RETICULATE_PYTHON_ENV
          source $RETICULATE_PYTHON_ENV/bin/activate
          python -V
          pip install -r requirements.txt
          pip list --format=columns
          deactivate

      - name: Build CmdStan
        run: |
          mkdir -p /opt/cmdstan
          curl -fLo cmdstan-${CMDSTAN_VERSION}.tar.gz https://github.com/stan-dev/cmdstan/releases/download/v${CMDSTAN_VERSION}/cmdstan-${CMDSTAN_VERSION}.tar.gz
          tar -xzf cmdstan-${CMDSTAN_VERSION}.tar.gz -C /opt/cmdstan/
          cd ${CMDSTAN}
          make build

      - name: Configure R CXXFLAGS/CXX14FLAGS
        run: |
          mkdir -p ~/.R
          echo "CXXFLAGS += -Wno-ignored-attributes" >> ~/.R/Makevars
          echo "CXX14 = g++ -flto=2" >> ~/.R/Makevars
          echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars
          echo $PATH

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('DESCRIPTION') }}
          restore-keys: r-

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install R packages
        run: |
          R -e 'install.packages(c("remotes", "BiocManager"))'
          xvfb-run --auto-servernum R -e 'update.packages(ask = F, checkBuilt = T, lib.loc = .libPaths()[1])'
          xvfb-run --auto-servernum R -e 'remotes::install_deps(dependencies = TRUE)'
          R -e "install.packages('spDataLarge', repos = 'https://nowosad.github.io/drat')"
          R -e "BiocManager::install(c('graph', 'Rgraphviz'))"
          xvfb-run --auto-servernum R -e 'install.packages(c("cmdstanr", "INLA", "spatialreg"), repos = c("https://mc-stan.org/r-packages/", "https://inla.r-inla-download.org/R/stable", getOption("repos")), dependencies = T)'

      - name: Check R packages
        run: |
          R -e 'sessionInfo(sort(.packages(T)))'
          # check TinyTeX
          R -e 'tinytex:::is_tinytex()'
          # check phantomjs
          R -e 'webshot::is_phantomjs_installed()'

      - name: Install Fonts
        run: |
          sudo apt-get install -y fonts-urw-base35 fonts-dejavu fonts-liberation fonts-noto-color-emoji
          fc-list | grep 'dejavu' | sort
          fc-list | grep 'liberation' | sort
          fc-list | sort
          mkdir -p ~/.fonts/fira
          curl -fLo Adobe-Fonts.zip https://github.com/XiangyunHuang/fonts/releases/download/v0.1/Adobe-Fonts.zip
          unzip Adobe-Fonts.zip -d ~/.fonts/adobe
          curl -fLo ~/.fonts/xkcd.ttf http://simonsoftware.se/other/xkcd.ttf
          cp -r ~/.TinyTeX/texmf-dist/fonts/opentype/public/fira  ~/.fonts/
          fc-cache -fsv
          R -e 'library(showtext);font_install(source_han_serif());font_install(source_han_sans());hrbrthemes::import_roboto_condensed()'
          # XKCD
          R -e 'library(extrafont);font_import(pattern="[X/x]kcd.ttf", prompt = FALSE)'

      - name: Build Book
        run: |
          export PATH=$HOME/bin:$PATH
          make gitbook
          # if make gitbook; then make pdf; fi

      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Upload Book
          path: _book

      - name: Install npm
        uses: actions/setup-node@v1

      - name: Deploy to Netlify
        # NETLIFY_AUTH_TOKEN added in the repo's secrets
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          export COMMIT_MSG=$(git log -1 --format='%h %<(50,trunc)%s')
          export DEPLOY_MSG=${COMMIT_MSG//[\'\"\`]/}
          npm install netlify-cli -g
          netlify deploy --prod --dir _book --message "$DEPLOY_MSG" --timeout 100
